[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[processes]
web = "/opt/venv/bin/python -m uvicorn asgi:app --host 0.0.0.0 --port $PORT"
worker = "/opt/venv/bin/python src/main.py"

